name: spotify-karaoke
channels:
 - defaults
dependencies:
 - cudatoolkit=10.0.130
 - cudnn=7.3.1
 - pip
 - pip:
  #  - tensorflow-gpu==2.5
   - spleeter
   - boto3
   - gql[all]
   - nltk
   - pytube
   - Requests
   - protobuf==3.20
   - git+https://github.com/m-bain/whisperx.git